language: node_js
sudo: required
dist: trusty
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
before_script:
  - jdk_switcher use oraclejdk8
after_success:
  - cat ./coverage/lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js
